#!/usr/bin/env python
'''
goatdctl - goatd control

Usage:
    goatdctl info
    goatdctl stop
    goatdctl heading
    goatdctl position
    goatdctl spin
    goatdctl rudder <angle>
    goatdctl sail <angle>

Options:
    -h --help     Show this screen.
    --version     Show goatd version

'''

from docopt import docopt

from goatd_client import Goat

if __name__ == '__main__':
    goat = Goat()
    args = docopt(__doc__, version=goat.version, options_first=True)
    if args['rudder']:
        print 'setting rudder to', args['<angle>']
        goat.rudder(float(args['<angle>']))

    if args['sail']:
        print 'setting sail to', args['<angle>']
        goat.sail(float(args['<angle>']))

    if args['spin']:
        import time
        for i in range(90):
            a = 45 - (i)
            goat.rudder(a)
